from pydantic import BaseModel, Field


class RealtimeCallCreate(BaseModel):
    """The WebRTC offer generated in the browser."""

    sdp: str = Field(min_length=1, max_length=200_000)


class RealtimeCallResponse(BaseModel):
    """The WebRTC answer generated by OpenAI."""

    sdp: str